language: cpp

os: osx
osx_image: xcode10.2
compiler: clang

addons:
  homebrew:
    packages:
    - cmake

branches:
  only:
  - master

# before_install:
#   - export PATH=/opt/local/bin:/opt/local/sbin:$PATH

script:
  - cd External && ./build_crossguid.sh && ./build_opengex.sh && ./build_zlib.sh && cd ..
  - mkdir -p build
  - cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . --config Debug
  - cmake --build . --target test